# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - dc-ai-hub

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: 'Create .npmrc'
        shell: bash
        run: |

          echo "registry=https://registry.npmjs.org/" > .npmrc
          echo "@boschrexroth:registry=https://lo-artifact.de.bosch.com/artifactory/api/npm/npm-automationx/" > .npmrc
          echo "//lo-artifact.de.bosch.com/artifactory/api/npm/npm-automationx/:_auth = ${{ secrets.JFROG_NPM_AUTH_TOKEN }}" >> .npmrc
          echo "//lo-artifact.de.bosch.com/artifactory/api/npm/npm-automationx/:always-auth = true" >> .npmrc
          echo "legacy-peer-deps = true" >> .npmrc
          echo "progress = true" >> .npmrc
          echo "loglevel = verbose" >> .npmrc
          echo "strict-ssl = false" >> .npmrc
          echo "fetch-retries = 99" >> .npmrc

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install
        run: |
          npm install -g @remix-run/dev
          npm install

      - name: npm build
        run: |
          npm run build

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'dc-ai-hub'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_607CAC7DCE6B4220B00A203C11F7A7EB }}